name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install marko jsonschema
    - name: Checks line length
      run: |
        test `grep -v "^|" draft/spec/index.md | cut -c121- | grep -vx "^$" | wc -l` -eq 0
        test `grep -v "^|" draft/implementation-notes/index.md | cut -c121- | grep -vx "^$" | wc -l` -eq 0
    - name: Checks Examples
      run: python scripts/check_examples.py
